### ISSUE TITLE
Transfer blocked

### ISSUE THREAD

**Issue by noLemonsNoMelon** [ton-blockchain/bridge#10]
### Bug Type

Functional

### Reproduction steps

The transfer of 189 Toncoins to my ETH wallet in blocked since the 15th of September at that stage:

_Please send 189 Toncoins to bridge smart-contract
ton://transfer/Ef_dJMSh8riPi3BTUTtcxsWjG8RLKnLctNjAM4rw8NN-xWdr?amount=189000000000&text=swapTo%230x37AEc2350De679780078C1855b1493d8877Bf9Af
Send from your personal wallet. Do not send directly from exchanges and bots!_

The 189 Toncoins have been sent to the wallet Ef_dJMSh8riPi3BTUTtcxsWjG8RLKnLctNjAM4rw8NN-xWdr but never reached my ETH wallet

### Actual result

Transfer not completed

### Expected result

Transfer of 189 Toncoins to my ETH wallet

### Suggested Severity

High

### Device

Desktop (please complete the following information):
- OS: Windows 10
- Browser Chrome
- Version 105.0.5195.125

**Comment by EmelyanenkoK** [comment]
Please contact @ton_help_bot to rescue funds

**Comment by RoseRompkxm** [comment]
> Please contact @ton_help_bot to rescue funds

How to contact this account? I didn't receive my funds as well
